Repository varshilpatel0107/Assignment-1, pull requests merged in 2021-10, with the labels that each got.

#3 1st pull
  README.md
Labels: Hacktoberfest, hacktoberfest2021

#4 Update README.md
  README.md
Labels: Hacktoberfest, hacktoberfest2021, hacktorberfest-accepted

#5 Update README.md
  README.md
Labels: Hacktoberfest, hacktoberfest2021, hacktorberfest-accepted, hacktober-fest
